@extends('layouts.website')
@section('content')
    <div id="main-page" class="col-md-12" style="background-color:#fff;padding-top:140px;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>Cookies Policy</h2>
                    <br>
                    <br> Il nostro sito Web fa uso di cookie allo scopo di migliorare l'esperienza online di tutti i nostri utenti. <br> <br> All'interno della nostra Policy sui Cookie descriviamo cosa sono i cookie e in che modo vengono usati sul nostro sito internet. Ti invitiamo a consultare la nostra Privacy Policy per ulteriori informazioni su come vengono usati i dati personali degli utenti che si collegano ai nostri siti internet e sull'importanza con cui consideriamo la protezione della tua privacy. <br> <br> Il nostro sito web e i servizi in esso contenuti non possono essere usati senza la presenza di Cookie e pertanto nell'utilizzare la nostra piattaforma Web, acconsenti all'uso di Cookie in conformità con i termini di detta politica. <br> <br> <br> <strong>Cosa sono i Cookie?</strong> <br> <br> I Cookie sono file di testo che contengono stringhe di testo di piccola dimensione inviate da un server Web ad un client (di solito un browser) e poi rimandati indietro dal client al server (senza subire modifiche) ogni volta che il client accede alla stessa porzione dello stesso dominio Web. I Cookie non contengono alcuna informazione in grado di identificare direttamente un utente, tuttavia, le informazioni personali conservate nel nostro sito possono essere collegate, da parte nostra, alle informazioni memorizzate nei Cookie e ottenute dai Cookie.	<br>
                    <br>
                    <br> <strong>Uso dei Cookie</strong> <br> <br> Le informazioni che otteniamo in seguito all'uso dei nostri Cookie sono utilizzate per i seguenti scopi: <ul> <li>Per riconoscere il computer dell'utente quando visita il nostro sito Web</li> <li>Per migliorare l'usabilità del sito Web</li> <li>Per analizzare l'utilizzo del sito Web</li> <li>Per amministrare questo sito Web</li> <li>Per prevenire le frodi e migliorare la sicurezza del sito Web</li> <li>Per personalizzare il nostro sito Web (con messaggi mirati che possono essere di interesse per l'utente)</li> <li>Per tenere traccia della navigazione dell'utente durante la sua visita</li> </ul> <br> <br> <strong>L'abilitazione dei Cookie è sicura?</strong><br> <br> Sì. I Cookie contengono solo piccole porzioni di dati e non possono eseguire alcuna operazione in maniera autonoma. Ti raccomandiamo di configurare il browser Web in modo tale da accettare Cookie provenienti dal nostro sito. <br> <br> <br> <strong>Come puoi modificare le impostazioni per i Cookie?</strong><br> <br> Per modificare le impostazioni riguardo ai Cookie, devi variare le impostazioni del browser che utilizzi. Dato che i browser vengono aggiornati di frequente e le piattaforme che li supportano sono sempre più numerose, non è possibile fornire un'unica guida idonea a tutte le versioni di browser e dispositivi. Tuttavia i seguenti collegamenti rimandano ad una ricerca Google con le opportune parole chiave relative alla modifica dei Cookie per ogni principale browser. Personalizza la ricerca inserendo la versione del browser e la piattaforma che utilizzi (PC, MAC, iPhone, Android, BlackBerry eccetera). <ul> <li>Internet Explorer</li> <li>Mozilla Firefox</li> <li>Chrome</li> <li>Safari</li> </ul>	<br>
                    <br> <strong>Quanti tipi di Cookie esistono?</strong> <br> <br> Sul nostro sito Web vengono utilizzati tre tipi diversi di Cookie:  <ul> <li><strong>Cookie di sessione</strong>: file temporanei che vengono memorizzati solo per la durata della sessione di navigazione sul sito Web. Il browser Web normalmente li elimina alla chiusura.</li> <li><strong>Cookie persistenti</strong>: la durata di questi file supera la sessione del browser (ad esempio, se si esegue l'accesso a un sito Web, questo riconosce l'utente alla sua visita successiva). I Cookie persistenti consentono funzionalità come avvisi di benvenuto, mantenimento degli oggetti nel carrello (in caso di acquisti online), riconoscimento delle preferenze come lingue, colori eccetera.</li> <li><strong>Cookie di terze parti</strong>: durante la navigazione del nostro sito Web, l'utente potrebbe trasmettere Cookie a terze parti non legate alla nostra azienda. Se si accede a una pagina Web con contenuti incorporati, ad esempio YouTube, potrebbero essere trasmessi dei Cookie da e verso tale sito. Non abbiamo il controllo di questi Cookie, pertanto ti consigliamo di consultare i siti Web di terze parti per maggiori informazioni riguardanti i Cookie di cui fanno uso e come gestirli.</li> </ul>
                    <br>
                    <br> <strong>Cookie presenti sul nostro sito internet</strong><br> <br> Di seguito viene riportato un elenco dei Cookie utilizzati dal nostro sito, con una spiegazione del singolo utilizzo: <ul> <li>Proprietario Tipo di Cookie Utilizzo</li> <li>Questo sito Temporaneo Sessione</li> <li>Google Persistente Statistiche utilizzo</li> <li>Facebook Persistente Login</li> <li>Twitter Persistente Login</li> <li>Blocco dei Cookie.</li> </ul> <br> Tutti i browser consentono di rifiutare i Cookie. Dato che i browser vengono aggiornati di frequente e le piattaforme che li supportano sono sempre più numerose, non è possibile fornire un'unica guida idonea a tutte le versioni di browser e dispositivi. <br> Il blocco dei Cookie, tuttavia, può avere un impatto negativo sull'usabilità di molti siti Web. <br> <br> <br> <strong>Eliminazione dei Cookie</strong><br> <br> È possibile eliminare i Cookie già memorizzati sul proprio computer. Dato che i browser vengono aggiornati di frequente e le piattaforme che li supportano sono sempre più numerose, non è possibile fornire un'unica guida idonea a tutte le versioni di browser e dispositivi. <br> Questa azione può avere conseguenze negative riguardo l'usabilità di molti siti Web. <br> <br> <br> <strong>Altre tecnologie presenti sul nostro sito</strong><br> <br> <em>Google Analytics</em> <br> Google Analytics è uno strumento di analisi di Google che aiuta i proprietari di siti web e app a capire come i visitatori interagiscono con i contenuti di loro proprietà. Si può utilizzare un set di cookie per raccogliere informazioni e generare statistiche di utilizzo del sito web senza identificazione personale dei singoli visitatori da parte di Google.<br> <br> <em>Google Maps</em><br> Google Maps è un servizio di visualizzazione di mappe gestito da Google Inc. che migliora notevolmente l'esperienza degli utenti sul nostro sito web. Google Maps, infatti, fornisce informazioni dettagliate sulla localizzazione di uno specifico esercizio commerciale o attività ricettiva presente sul territorio.<br>
                    <br>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js_script')
    <script>

    </script>
@stop